comment out SSL configuration in TypeORM setup due to error
```
[Nest] 15942  - 11/11/2025, 2:16:27 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: The server does not support SSL connections
    at Socket.<anonymous> (/Users/gmnnggn/Documents/code/csc185/bansay-api/node_modules/pg/lib/connection.js:76:37)
    at Object.onceWrapper (node:events:623:26)
    at Socket.emit (node:events:508:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
```